// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBG-Hz_wYJrHHWx3YyVE9FWZA5rdbuCk',
    appId: '1:835267182975:web:c7849d402c4a764ab49a4a',
    messagingSenderId: '835267182975',
    projectId: 'flutter-pinjam-ruang-38271',
    authDomain: 'flutter-pinjam-ruang-38271.firebaseapp.com',
    storageBucket: 'flutter-pinjam-ruang-38271.appspot.com',
    measurementId: 'G-DVHVE0BKLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4A3gsg2lZySoaenvdp1UVdcV-SSy5MXk',
    appId: '1:835267182975:android:8009119491c4bf88b49a4a',
    messagingSenderId: '835267182975',
    projectId: 'flutter-pinjam-ruang-38271',
    storageBucket: 'flutter-pinjam-ruang-38271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbBbqPiu2MlYvZCUt7CQU_iR7LnmcTqg',
    appId: '1:835267182975:ios:58f79b5d470a3728b49a4a',
    messagingSenderId: '835267182975',
    projectId: 'flutter-pinjam-ruang-38271',
    storageBucket: 'flutter-pinjam-ruang-38271.appspot.com',
    iosBundleId: 'com.teknokrat.flutterPinjamRuang',
  );
}
